import pandas as pd

# bizdev.csv is generated by running scrupp.com against https://www.linkedin.com/sales/search/people?query=(spellCorrectionEnabled%3Atrue%2CrecentSearchParam%3A(id%3A2120154954%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3AINDUSTRY%2Cvalues%3AList((id%3A80%2Ctext%3AAdvertising%2520Services%2CselectionType%3AEXCLUDED)))%2C(type%3ACOMPANY_HEADQUARTERS%2Cvalues%3AList((id%3A103644278%2Ctext%3AUnited%2520States%2CselectionType%3AINCLUDED)))%2C(type%3ACOMPANY_HEADCOUNT%2Cvalues%3AList((id%3AC%2Ctext%3A11-50%2CselectionType%3AINCLUDED)%2C(id%3AD%2Ctext%3A51-200%2CselectionType%3AINCLUDED)%2C(id%3AE%2Ctext%3A201-500%2CselectionType%3AINCLUDED)))%2C(type%3ARELATIONSHIP%2Cvalues%3AList((id%3AS%2Ctext%3A2nd%2520Degree%2520Connections%2CselectionType%3AINCLUDED)%2C(id%3AO%2Ctext%3A3rd%2520Degree%252B%2520Connections%2CselectionType%3AINCLUDED)))%2C(type%3ATITLE%2Cvalues%3AList((text%3Asales%2CselectionType%3AINCLUDED)%2C(text%3A%2522business%2520development%2522%2CselectionType%3AINCLUDED)%2C(text%3Amarketing%2CselectionType%3AINCLUDED))%2CselectedSubFilter%3ACURRENT))%2Ckeywords%3A%2522custom%2520software%2522)&sessionId=cGk2K2M9TBmplRqLIKFzgQ%3D%3D
# founders.csv is generated by running scrupp.com against https://www.linkedin.com/sales/search/people?query=(spellCorrectionEnabled%3Atrue%2CrecentSearchParam%3A(id%3A2120154954%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3AINDUSTRY%2Cvalues%3AList((id%3A80%2Ctext%3AAdvertising%2520Services%2CselectionType%3AEXCLUDED)))%2C(type%3ACOMPANY_HEADQUARTERS%2Cvalues%3AList((id%3A103644278%2Ctext%3AUnited%2520States%2CselectionType%3AINCLUDED)))%2C(type%3ACOMPANY_HEADCOUNT%2Cvalues%3AList((id%3AC%2Ctext%3A11-50%2CselectionType%3AINCLUDED)%2C(id%3AD%2Ctext%3A51-200%2CselectionType%3AINCLUDED)%2C(id%3AE%2Ctext%3A201-500%2CselectionType%3AINCLUDED)))%2C(type%3ASENIORITY_LEVEL%2Cvalues%3AList((id%3A10%2Ctext%3AOwner%2CselectionType%3AINCLUDED)%2C(id%3A9%2Ctext%3APartner%2CselectionType%3AINCLUDED)))%2C(type%3ARELATIONSHIP%2Cvalues%3AList((id%3AS%2Ctext%3A2nd%2520Degree%2520Connections%2CselectionType%3AINCLUDED)%2C(id%3AO%2Ctext%3A3rd%2520Degree%252B%2520Connections%2CselectionType%3AINCLUDED))))%2Ckeywords%3A%2522custom%2520software%2522)&sessionId=cGk2K2M9TBmplRqLIKFzgQ%3D%3D&viewAllFilters=true

# Load the CSV files into two DataFrames
founders_df = pd.read_csv('founders.csv')
bizdev_df = pd.read_csv('bizdev.csv')

# Filter founders_df on the 'company' column (tilde is the negation symbol)
filtered_df = founders_df[~founders_df.company_name.isin(bizdev_df.company_name)]

dropped_rows_df = founders_df[founders_df.company_name.isin(bizdev_df.company_name)]


# Sanity-checking resulting DataFrames
print("filtered_df: " + str(len(filtered_df.index)) + " rows")
print(filtered_df[['first_name', 'last_name', 'position', 'company_name']].head())

print ("\n\ndropped_rows_df: " + str(len(dropped_rows_df.index)) + " rows")
print(dropped_rows_df[['first_name', 'last_name', 'position', 'company_name']])

# Write the DataFrame to a CSV file
filtered_df.to_csv('filtered.csv', index=False)
